# Generated by Django 3.1.2 on 2020-11-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristicsorganization',
            options={'managed': True, 'ordering': ['id_institution'], 'verbose_name': 'Характеристики организации'},
        ),
        migrations.RenameField(
            model_name='characteristicsorganization',
            old_name='id_institutions',
            new_name='id_institution',
        ),
        migrations.RenameField(
            model_name='characteristicsorganization',
            old_name='name_institutions',
            new_name='name_institution',
        ),
        migrations.RenameField(
            model_name='characteristicsorganization',
            old_name='type_institutions',
            new_name='type_institution',
        ),
        migrations.RenameField(
            model_name='characteristicsorganization',
            old_name='type_organizations',
            new_name='type_organization',
        ),
        migrations.AlterUniqueTogether(
            name='characteristicsorganization',
            unique_together={('id_institution', 'name_institution', 'inn')},
        ),
    ]
