# Generated by Django 3.1.2 on 2020-10-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headbybk',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='data',
            name='budget_level',
        ),
        migrations.AlterField(
            model_name='data',
            name='id_head_by_bk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_view.headbybk', verbose_name=''),
        ),
        migrations.AlterModelTable(
            name='headbybk',
            table='head_by_bk_manual',
        ),
        migrations.CreateModel(
            name='TypeOrganizations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('outside_id', models.IntegerField(verbose_name='outside_id')),
                ('type_organizations', models.TextField(verbose_name='Тип организации')),
            ],
            options={
                'db_table': 'type_organizations_manual',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('id', 'outside_id')},
            },
        ),
        migrations.CreateModel(
            name='TypeInstitutions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('outside_id', models.IntegerField(verbose_name='outside_id')),
                ('type_institutions', models.TextField(verbose_name='Тип учреждения')),
            ],
            options={
                'db_table': 'type_institutions_manual',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('id', 'outside_id')},
            },
        ),
        migrations.CreateModel(
            name='StatusRYBPNYBP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('outside_id', models.IntegerField(verbose_name='outside_id')),
                ('status_rybpnybp', models.TextField(db_column='status_RYBPNYBP', verbose_name='Статус РУБПНУБП')),
            ],
            options={
                'db_table': 'status_rybpnybp_manual',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('id', 'outside_id')},
            },
        ),
        migrations.CreateModel(
            name='StatusEGRUL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('outside_id', models.IntegerField(verbose_name='outside_id')),
                ('status_egrul', models.TextField(db_column='status_EGRUL', verbose_name='Статус ЕГРЮЛ')),
            ],
            options={
                'db_table': 'status_egrul_manual',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('id', 'outside_id')},
            },
        ),
        migrations.CreateModel(
            name='IndustrySpecificTyping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('industry_specific_typing', models.TextField(db_column='industry_specific_typing', verbose_name='Отраслевая типизация')),
            ],
            options={
                'db_table': 'industry_specific_typing_manual',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='BudgetLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('budget_level', models.TextField(verbose_name='Уровень бюджета')),
            ],
            options={
                'db_table': 'budget_level',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='industry_specific_typing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_view.industryspecifictyping', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='status_egrul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_view.statusegrul', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='status_rybpnybp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_view.statusrybpnybp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='type_institutions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_view.typeinstitutions', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='type_organizations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_view.typeorganizations', verbose_name=''),
        ),
    ]
