# Generated by Django 3.1.2 on 2020-10-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0002_auto_20201029_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='budget_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Data_view.budgetlevel', verbose_name=''),
            preserve_default=False,
        ),
    ]
