# Generated by Django 3.1.2 on 2020-10-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0003_data_budget_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='budget_level',
            new_name='id_budget_level',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='status_egrul',
            new_name='id_status_egrul',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='status_rybpnybp',
            new_name='id_status_rybpnybp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='type_institutions',
            new_name='id_type_institutions',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='type_organizations',
            new_name='id_type_organizations',
        ),
    ]
