# Generated by Django 3.1.2 on 2020-10-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0005_auto_20201030_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetlevel',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Уровнь бюджета'},
        ),
        migrations.AlterModelOptions(
            name='headbybk',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Глава по БК'},
        ),
        migrations.AlterModelOptions(
            name='industryspecifictyping',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': ' Отраслевая типизация'},
        ),
        migrations.AlterModelOptions(
            name='statusegrul',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Статус ЕГРЮЛ'},
        ),
        migrations.AlterModelOptions(
            name='statusrybpnybp',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Статус РУБПНУБП'},
        ),
        migrations.AlterModelOptions(
            name='typeinstitutions',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Тип учреждения'},
        ),
        migrations.AlterModelOptions(
            name='typeorganizations',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Тип организации'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_budget_level',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_head_by_bk',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_industry_specific_typing',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_status_egrul',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_status_rybpnybp',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_type_institutions',
        ),
        migrations.RemoveField(
            model_name='data',
            name='id_type_organizations',
        ),
        migrations.AddField(
            model_name='data',
            name='budget_level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.budgetlevel', verbose_name='Код уровня бюджета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='head_by_bk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.headbybk', verbose_name='Код уровня бюджета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='industry_specific_typing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.industryspecifictyping', verbose_name='Код отраслевой типизации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='status_egrul',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.statusegrul', verbose_name='Код статуса ЕГРЮЛ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='status_rybpnybp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.statusrybpnybp', verbose_name='Код статуса РУБПНУБП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='type_institutions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.typeinstitutions', verbose_name='Код типа учреждения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='type_organizations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_view.typeorganizations', verbose_name='Код типа организации'),
            preserve_default=False,
        ),
    ]
