# Generated by Django 3.1.2 on 2020-11-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0006_auto_20201030_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headbybk',
            options={'managed': True, 'verbose_name': 'Наименование главы по БК'},
        ),
        migrations.AlterModelOptions(
            name='industryspecifictyping',
            options={'managed': True, 'verbose_name': 'Наименование отраслевой типизации'},
        ),
        migrations.AlterModelOptions(
            name='statusegrul',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Наименование статуса ЕГРЮЛ'},
        ),
        migrations.AlterModelOptions(
            name='statusrybpnybp',
            options={'managed': True, 'verbose_name': 'Наименование статуса РУБПНУБП'},
        ),
        migrations.AlterModelOptions(
            name='typeinstitutions',
            options={'managed': True, 'verbose_name': 'Наименование типа учреждения'},
        ),
        migrations.AlterModelOptions(
            name='typeorganizations',
            options={'managed': True, 'verbose_name': 'Наименование типа организации'},
        ),
        migrations.RenameField(
            model_name='industryspecifictyping',
            old_name='industry_specific_typing',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='statusegrul',
            old_name='status_egrul',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='statusrybpnybp',
            old_name='status_rybpnybp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typeinstitutions',
            old_name='type_institutions',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typeorganizations',
            old_name='type_organizations',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='data',
            name='budget_level',
            field=models.IntegerField(choices=[(0, 'Не определен'), (1, 'Федеральный бюджет'), (2, 'Бюджет субъекта Российской Федерации'), (3, 'Местный бюджет'), (4, 'Бюджет городского округа'), (5, 'Бюджет муниципального района'), (6, 'Бюджет городского поселения'), (7, 'Бюджет сельского поселения'), (8, 'Бюджет государственного внебюджетного фонда Российской Федерации'), (9, 'Бюджет Пенсионного фонда Российской Федерации'), (10, 'Бюджет Фонда социального страхования Российской Федерации'), (11, 'Бюджет Федерального фонда обязательного медицинского страхования'), (12, 'Бюджет территориального государственного внебюджетного фонда'), (13, 'Бюджет городского округа с внутригородским делением'), (14, 'Бюджет внутригородского муниципального образования города федерального значения'), (15, 'Бюджет внутригородского района')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='head_by_bk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data_view.headbybk', verbose_name='Код уровня бюджета'),
        ),
        migrations.AlterField(
            model_name='data',
            name='industry_specific_typing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data_view.industryspecifictyping', verbose_name='Код отраслевой типизации'),
        ),
        migrations.AlterField(
            model_name='data',
            name='status_egrul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data_view.statusegrul', verbose_name='Код статуса ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='status_rybpnybp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data_view.statusrybpnybp', verbose_name='Код статуса РУБПНУБП'),
        ),
        migrations.AlterField(
            model_name='data',
            name='type_institutions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data_view.typeinstitutions', verbose_name='Код типа учреждения'),
        ),
        migrations.AlterField(
            model_name='data',
            name='type_organizations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data_view.typeorganizations', verbose_name='Код типа организации'),
        ),
        migrations.AlterField(
            model_name='headbybk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='industryspecifictyping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusegrul',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusrybpnybp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typeinstitutions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typeorganizations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BudgetLevel',
        ),
    ]
