# Generated by Django 3.1.2 on 2020-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0008_auto_20201106_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryspecifictyping',
            old_name='name',
            new_name='name_typing',
        ),
        migrations.RenameField(
            model_name='statusegrul',
            old_name='name',
            new_name='name_status',
        ),
        migrations.RenameField(
            model_name='statusrybpnybp',
            old_name='name',
            new_name='name_status',
        ),
        migrations.RenameField(
            model_name='typeinstitutions',
            old_name='name',
            new_name='name_type',
        ),
        migrations.RenameField(
            model_name='typeorganizations',
            old_name='name',
            new_name='name_type',
        ),
        migrations.AlterField(
            model_name='data',
            name='budget_level',
            field=models.IntegerField(choices=[(0, 'Не определен'), (1, 'Федеральный бюджет'), (2, 'Бюджет субъекта Российской Федерации'), (3, 'Местный бюджет'), (4, 'Бюджет городского округа'), (5, 'Бюджет муниципального района'), (6, 'Бюджет городского поселения'), (7, 'Бюджет сельского поселения'), (8, 'Бюджет государственного внебюджетного фонда Российской Федерации'), (9, 'Бюджет Пенсионного фонда Российской Федерации'), (10, 'Бюджет Фонда социального страхования Российской Федерации'), (11, 'Бюджет Федерального фонда обязательного медицинского страхования '), (12, 'Бюджет территориального государственного внебюджетного фонда'), (13, 'Бюджет городского округа с внутригородским делением'), (14, 'Бюджет внутригородского муниципального образования города федерального значения '), (15, 'Бюджет внутригородского района')], default=0),
        ),
    ]
