# Generated by Django 3.1.2 on 2020-11-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_view', '0009_auto_20201107_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusegrul',
            options={'managed': True, 'verbose_name': 'Наименование статуса ЕГРЮЛ'},
        ),
    ]
